In [1]:
import numpy as np
from numpy import linalg as LA

In [3]:
my_S = np.array([[1, 2, 3],[2,4,5],[3,5,6]])
my_N = np.array([[2, 2, 1],[2,2,1],[1,1,1]])

# E is the sum of the vectors
#E = np.nansum(np.dstack((my_S, my_N)),2)
E = my_S[0,1:]
E

array([2, 3])

In [5]:
NE = np.float64(my_N[0,1:])
NE

array([2., 1.])

In [6]:
Mean = E/NE
Mean

array([1., 3.])

In [8]:
O = my_S[1:,1:]
O

array([[4, 5],
       [5, 6]])

In [9]:
NO = np.float64(my_N[1:,1:])
NO

array([[2., 1.],
       [1., 1.]])