In [2]:
import numpy as np

A = np.mat("5 -3 0;-3 5 0;0 0 4")
print ("A\n", A)

print ("Eigenvalues", np.linalg.eigvals(A))





A
 [[ 5 -3  0]
 [-3  5  0]
 [ 0  0  4]]
Eigenvalues [8. 2. 4.]


In [4]:
eigenvalues, eigenvectors = np.linalg.eig(A)
print ("First tuple of eig", eigenvalues)
print ("Second tuple of eig\n", eigenvectors)




First tuple of eig [8. 2. 4.]
Second tuple of eig
 [[ 0.70710678  0.70710678  0.        ]
 [-0.70710678  0.70710678  0.        ]
 [ 0.          0.          1.        ]]


In [5]:
a = np.array([ [5, -3, 0], [-3, 5, 0], [0,   0,  4]]) 
b = np.corrcoef(a)
print (b)

[[ 1.         -0.95918367 -0.14285714]
 [-0.95918367  1.         -0.14285714]
 [-0.14285714 -0.14285714  1.        ]]
