In [1]:
import numpy as np
v1 = np.array([1,0,0])
v2 = np.array ([0,1,0])
v3 = np.array([0,0,1])

In [4]:
print( v1 + v2)

[1 1 0]


In [5]:
print (v1*v2)

[0 0 0]


In [8]:
print ((v1*v2)*v3)

[0 0 0]


In [9]:
print(-v3)

[ 0  0 -1]


In [10]:
print((v1*v1)**0.5)

[ 1.  0.  0.]


In [12]:
print((v2*v2)**0.5)

[ 0.  1.  0.]


In [15]:
print(((v1*v1)**0.5)+((v2*v2)**0.5))

[ 1.  1.  0.]
